### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by apoorvcodes** [bajpai244/bajpai244#1]
Oh wait i wanted to contact u, i miss placed ur number, we met at the lightspeed hackathon

**Comment by bajpai244** [comment]
Hey Apoorv! 

Can your provide me your email? Also you can also connect with me on [Twitter](https://twitter.com/bajpaiharsh244) and LinkedIn(https://www.linkedin.com/in/bajpaiharsh/)

Have an amazing day!

**Comment by apoorvcodes** [comment]
apoorvcodes381@gmail.com, twitter: apoorvcodes I'll like to have a chat with you
